adgroup_brand = {
	"1791": "brand1791",
	"1791 mail": "brand1791",
	"1791 mail - 1791mail": "brand1791",
	"1791 mail - email": "brand1791",
	"1791 mail - email #2": "brand1791",
	"1791 mail - paid email": "brand1791",
	"1791 mail - private email": "brand1791",
	"1791 mail - secure email": "brand1791",
	"1791 mail #2": "brand1791",
	"1791 mail #3": "brand1791",
	"1791 mail #4": "brand1791",
	"abandoners": "reagan",
	"abandoners - no age limit": "reagan",
	"abandoners-reagan": "reagan",
	"Anti T Shirts": "reagan",
	"checked email": "reagan",
	"clicked to cart or checked email- but did not check out": "reagan",
	"Confidential Mail": "mymailconfidential",
	"Conservative": "reagan",
	"Conservative email": "reagan",
	"Elections/Campaigns": "reagan",
	"email reagan": "reagan",
	"FBEmail": "faithbasedemail",
	"Health Care": "reagan",
	"Keywords": "reagan",
	"Michael Reagan": "reagan",
	"mike reagan": "reagan",
	"Misspellings": "reagan",
	"Political Polls/Surveys": "reagan",
	"Privacy Keywords [MMC]": "mymailconfidential",
	"Privacy Kws [Reagan]": "reagan",
	"Private email": "reagan",
	"reagan": "reagan",
	"Reagan Banner Ads - NB": "reagan",
	"reagan email": "reagan",
	"Reagan Names": "reagan",
	"Reagan.com": "reagan",
	"Republican Email": "reagan",
	"retargeting": "reagan",
	"Right Wing Politics": "reagan",
	"Secure Email": "reagan",
	"Similar to All Converters": "reagan",
	"Similar to Smart Pixel": "reagan",
	"Smart Pixel": "reagan",
	"Vanity Email": "reagan",
	"Vanity Email Address": "reagan",
	"We did build it": "reagan",
}
